# Site settings
title: 0xivy
description: Personal Portfolio of 0xivy


# User settings
username: 👁v
user_description: Security Engineer with an ack for scripting. Worked with Splunk, Splunk ES, Phantom, Exabeam. Built custom apps for Splunk and Phantom using python.
user_title: Security Engineer
email: samwovian18@gmail.com
twitter_username: frozenowo
github_username:  0xivy
linkedin_username:  sam1337

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
